version: "3.7"

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=heat_tags_dev
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local